site_name: ELIXIR lesson
nav:
    - Home: overview.md
    - General info: 
      - Precourse preparations: precourse.md
      - Course schedule: course_schedule.md
    - Chapters:
      - "Chapter 1": chapters/chapter_01.md
      - "Chapter 2": chapters/chapter_02.md
      - "Chapter 3": chapters/chapter_03.md
    - Keywords list: keywords.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png 
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.top
    - toc.integrate
    #- navigation.tabs
    #- navigation.sections
    #- navigation.indexes
    

# Repository
repo_name: elinkronander/ELIXIR-lesson-template
repo_url: https://github.com/elinkronander/ELIXIR-lesson-template
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  
# Footer
copyright: Licence; Creation of this material was funded by project# and is made availiable under a CC-BY licence

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
